apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  labels:
    type: local
    app: mysql
spec:
  storageClassName: manual
  # capacity:
  #   storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/gitpod/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  # resources:
  #   requests:
  #     storage: 8Gi
  selector:
    matchLabels:
      app: mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
  labels:
    type: local
spec:
  storageClassName: manual
  # capacity:
  #   storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/gitpod/minio"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  # resources:
  #   requests:
  #     storage: 8Gi
  selector:
    matchLabels:
      app: minio
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry
  labels:
    type: local
spec:
  storageClassName: manual
  # capacity:
  #   storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/gitpod/docker-registry"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  # resources:
  #   requests:
  #     storage: 8Gi
  selector:
    matchLabels:
      app: docker-registry
