packages:
  - name: all
    type: generic
    argdeps:
      - version
    deps:
      - install/installer:docker
      - install/docker/gitpod-image:docker
      - install/docker/examples/gitpod-gitlab/gitlab:docker
